spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookspud?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: ${spring.datasource.local_password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

# S3
cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: bookspud
    stack:
      auto: false

